### PR TITLE
Fixed JWTBody generic type

### LINKED ISSUE #37: JWTBody type is incorrect
You define JWTBody as:

```
export type JWTBody<T = any> = Record<string, T>;
```

If we take a look what your docs say: 
```
const foo = JWT.decode(token, key);
// foo.body === any

type MyType = Record<string, number>;
const bar = JWT.decode<MyType>(token, key);
// bar.body === MyType
```
Which is obviously incorrect.

`foo.body` is of type `Record<string, any>`, not `any`.
`bar.body` is of type `Record<string, MyType>` (if we expand this further we get `Record<string, Record<string, number>>`) not `MyType`.

If you are not adept at TypeScript, I suggest looking at jwt-decode library source and how they did types there.

### PR DESCRIPTION
**Pull request by dPreininger**
This PR fixes #37.

Standard claims set was taken from jwt-decode, which should be up to date with the JWT standard, but didn't double check.

Also changed parseToNumber function.
- JWT body fields such as exp are numbers, not number strings (at least in most implementations). To still allow number strings in these fields and not potentially break any existing implementations, the function is still called, but I did change the function signature.
- parseToNumber function would return null, if the input to the function is '0' or 0. Now, it would return 0. I know that exp and similar fields shouldn't really ever have the value of 0, but maybe in the future this function will be also used elsewhere.
- JavaScript parseInt function already works with number values, but TypeScript complains when trying to pass a number to that function. Therefore, I have added a number type check to satisfy TypeScript.
- This function will produce the same output as before in all scenarios, except when '0' or 0 is passed in as input, therefore no breaking changes are introduced.

### CODE REVIEW

File: lib/decoder.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ class Decoder {
     }
     this.verifyClaims();
 
-    return this._body;
+    return this._body as JWTBody<T>;
```
Comment (blake-simpson) [inline lib/decoder.ts]: Using `as` in TypeScript is generally an anti-pattern. You are needing to do this as the Decoder class is no longer correctly typed.

It would be better to pass the `T` generic to the class itself, then you don't have to use this hack and can apply it to the class variable definition instead.

```ts
class Decoder<T> {
  _header: JWTHeader;
  _body: JWTBody<T>;
  
  ...
  
   decodeAndVerify(token: JWTToken, options: DecodingOptions = {}): JWTBody<T> {
     ...
     return this._body;
  }
```

Then in the index.ts you can simply pass the type as:

```ts
const decoder = new Decoder<T>(key);
return decoder.decodeAndVerify(token, options);
```

File: lib/verifier.ts [hunk 2]
```diff
@@ -12,8 +12,21 @@ const claims = [
...
-const parseToNumber = (value?: string) =>
-  value ? parseInt(value) || null : null;
+const parseToNumber = (value?: string | number) => {
+  if(typeof(value) === 'number') {
+    return value;
+  } else if(typeof(value) === 'string') {
+    const parsed = parseInt(value);
+
+    if (isNaN(parsed)) {
+      return null;
```
Comment (blake-simpson) [inline lib/verifier.ts]: `0` is falesy in classic JS for a reason. As you mentioned the numbered claims should never be `0`.

The claims functions must be able to handle strings for pure JS implementations of this library.

Since you have defined the `JWTStandardClaims` as optional props though (without mentioning null), it would be better to return `undefined` here instead of `null`. Also, leaving the `0` return as undefined will be less of a potential breaking change.

I would simplify this to:

```ts
const parseToNumber = (value?: string | number) =>
  value ? parseInt(value.toString()) || undefined : undefined;
```

**Comment by dPreininger** [comment]
Just checked the JWT spec and nbf, exp and iat fields must be numbers, therefore number strings shouldn't be allowed according to specification. I guess the parseToNumber calls for those fields could be omitted but that would be a potentially breaking change. It is your call if you want to do that or not.

File: types/jwt.ts [hunk 3]
```diff
@@ -1,6 +1,16 @@
 import { SupportedAlgorithms } from './algorithms';
 
-export type JWTBody<T = any> = Record<string, T>;
+export type JWTStandardClaims = {
```
Comment (blake-simpson) [inline types/jwt.ts:3]: This is a nice idea 👍

File: types/jwt.ts [hunk 4]
```diff
@@ -1,6 +1,16 @@
...
+  iss?: string;
+  sub?: string;
+  aud?: string[] | string;
+  exp?: number;
+  nbf?: number;
+  iat?: number;
+  jti?: string;
+}
+
+export type JWTBody<T = Record<string, any>> = T & JWTStandardClaims;
```
Comment (blake-simpson) [inline types/jwt.ts]: Perhaps to be cleaner:

```ts
type DefaultJWTBody = Record<string, any>;
export type JWTBody<T = DefaultJWTBody> = T & JWTStandardClaims;
```

Not a blocker though.

**Review by blake-simpson — CHANGES_REQUESTED** [review]

**Comment by dPreininger** [comment]
Implemented all the changes, also had to change a test, as decoder class is now generic and not the decode function.
